# Generated by Django 3.2.8 on 2023-01-18 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_player_sex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='sex',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
